// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-07-07 00:56:07.116711627 +0000 UTC m=+0.006095109
package cmd

const GITVERSION = `3146beb run make release`
const SEMVER = "1.0.0"
const DEPENDENCIES = `module gitlab.com/elixxir/user-discovery-bot

go 1.13

require (
	github.com/go-pg/pg v8.0.6+incompatible
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/mattn/go-shellwords v1.0.10
	github.com/mitchellh/go-homedir v1.1.0
	github.com/mitchellh/mapstructure v1.3.2 // indirect
	github.com/onsi/ginkgo v1.12.0 // indirect
	github.com/onsi/gomega v1.10.0 // indirect
	github.com/pelletier/go-toml v1.8.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/smartystreets/assertions v1.1.0 // indirect
	github.com/spf13/afero v1.3.1 // indirect
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/viper v1.7.0
	gitlab.com/elixxir/client v1.2.1-0.20200707005425-f74eb9af6521
	gitlab.com/elixxir/comms v0.0.0-20200707005357-086c7bd56eae
	gitlab.com/elixxir/crypto v0.0.0-20200707005343-97f868cbd930
	gitlab.com/elixxir/primitives v0.0.0-20200706165052-9fe7a4fb99a3
	golang.org/x/net v0.0.0-20200625001655-4c5254603344 // indirect
	golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae // indirect
	golang.org/x/text v0.3.3 // indirect
	google.golang.org/genproto v0.0.0-20200707001353-8e8330bf89df // indirect
	google.golang.org/grpc v1.30.0 // indirect
	google.golang.org/protobuf v1.25.0 // indirect
	gopkg.in/ini.v1 v1.57.0 // indirect
	mellium.im/sasl v0.2.1 // indirect
)
`
