// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-11-11 13:28:35.303815 -0600 CST m=+0.058009400
package cmd

const GITVERSION = `71c1747 Merge branch 'master' into release`
const SEMVER = "2.1.1"
const DEPENDENCIES = `module gitlab.com/elixxir/user-discovery-bot

go 1.13

require (
	github.com/golang/protobuf v1.5.2
	github.com/magiconair/properties v1.8.5 // indirect
	github.com/mitchellh/mapstructure v1.4.1 // indirect
	github.com/pelletier/go-toml v1.9.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.1.3
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/viper v1.7.1
	github.com/ttacon/libphonenumber v1.2.1
	gitlab.com/elixxir/client v1.5.1-0.20211111192117-4c954e272adf
	gitlab.com/elixxir/comms v0.0.4-0.20211101174956-590ba1b47887
	gitlab.com/elixxir/crypto v0.0.7-0.20211022013957-3a7899285c4c
	gitlab.com/elixxir/primitives v0.0.3-0.20211102233208-a716d5c670b6
	gitlab.com/xx_network/comms v0.0.4-0.20211014163953-e774276b83ae
	gitlab.com/xx_network/crypto v0.0.5-0.20211014163843-57b345890686
	gitlab.com/xx_network/primitives v0.0.4-0.20211014163031-53405cf191fb
	google.golang.org/genproto v0.0.0-20210427215850-f767ed18ee4d // indirect
	gorm.io/driver/postgres v1.1.2
	gorm.io/gorm v1.21.15
)
`
